# Generated by Django 6.1.1 on 2026-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_nascimento', models.DateField()),
                ('tipo_usuario', models.CharField(choices=[('pescador', 'Pescador'), ('outro', 'Outro')], max_length=50)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('avançado', 'Avançado'), ('outro', 'Outro')], max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nome'],
            },
        ),
    ]
